[colors]
background = "#111416"
foreground = "#eeeeec"
dim-foreground = "#9d9d9c"
cursor = "#00e6ff"
black = "#000000"
red = "#cd0000"
green = "#00cd00"
yellow = "#cdcd00"
blue = "#1093f5"
magenta = "#cd00cd"
cyan = "#00cdcd"
white = "#faebd7"
light-black = "#8b949e"
light-red = "#ff0000"
light-green = "#00ff00"
light-yellow = "#ffff00"
light-blue = "#11b5f6"
light-magenta = "#ff00ff"
light-cyan = "#00ffff"
light-white = "#ffffff"
