[[mgr.prepend_keymap]]
on = ["<Tab>"]
run = "plugin quick-search -- --source=tab"
desc = "Search recent folders"

[[mgr.prepend_keymap]]
on = ["Z"]
run = "plugin quick-search -- --source=zoxide"
desc = "Jump to a recent folder"

[[mgr.prepend_keymap]]
on = ["<BackTab>"]
run = "spot"
desc = "Spot hovered file"

[[mgr.prepend_keymap]]
on = ["<S-Tab>"]
run = "spot"
desc = "Spot hovered file"

[[mgr.append_keymap]]
on = ["<A-Enter>"]
run = "plugin tab-workspace"
desc = "Set popup selection or location as tab folder"

[[mgr.append_keymap]]
on = ["<A-r>"]
run = 'shell "$YZX_YAZI_RETURN"'
desc = "Return from Yazi"
