[[mgr.append_keymap]]
on = ["<A-Enter>"]
run = "plugin tab-workspace"
desc = "Use current folder as tab workspace"

[[mgr.append_keymap]]
on = ["<A-r>"]
run = 'shell "$YZX_YAZI_RETURN"'
desc = "Return from Yazi"
