[[mgr.prepend_keymap]]
on = ["<BackTab>"]
run = "spot"
desc = "Spot hovered file"

[[mgr.prepend_keymap]]
on = ["<S-Tab>"]
run = "spot"
desc = "Spot hovered file"

[[mgr.append_keymap]]
on = ["<A-Enter>"]
run = "plugin tab-workspace"
desc = "Use hovered folder or current folder as tab workspace"

[[mgr.append_keymap]]
on = ["<A-r>"]
run = 'shell "$YZX_YAZI_RETURN"'
desc = "Return from Yazi"
